apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin
  namespace: portfolio
  labels:
    app.kubernetes.io/name: admin
    app.kubernetes.io/part-of: portfolio
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - admin.borowski.services
      secretName: admin-tls
  rules:
    - host: admin.borowski.services
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin
                port:
                  number: 80
